#ifndef HD44780_HD44780_SETTINGS_H_
#define HD44780_HD44780_SETTINGS_H_

//! LIBRARY SETTINGS
#define HD44780_USE_BUSY_FLAG 1

//! PLATFORM HEADER
#include <stm32f0xx.h>

#define LCD_RS_GPIO 		GPIOB
#define LCD_RS_PIN 			6
#define LCD_RS_GPIO_CONFIG 	LCD_RS_GPIO, LCD_RS_PIN

#define LCD_E_GPIO 			GPIOB
#define LCD_E_PIN 			3
#define LCD_E_GPIO_CONFIG 	LCD_E_GPIO, LCD_E_PIN

#define LCD_RW_GPIO 		GPIOB
#define LCD_RW_PIN 			9
#define LCD_RW_GPIO_CONFIG 	LCD_RW_GPIO, LCD_RW_PIN

#define LCD_DB4_GPIO 		GPIOB
#define LCD_DB4_PIN 		5
#define LCD_DB4_GPIO_CONFIG LCD_DB4_GPIO, LCD_DB4_PIN

#define LCD_DB5_GPIO 		GPIOB
#define LCD_DB5_PIN 		4
#define LCD_DB5_GPIO_CONFIG LCD_DB5_GPIO, LCD_DB5_PIN

#define LCD_DB6_GPIO 		GPIOB
#define LCD_DB6_PIN 		10
#define LCD_DB6_GPIO_CONFIG LCD_DB6_GPIO, LCD_DB6_PIN

#define LCD_DB7_GPIO 		GPIOB
#define LCD_DB7_PIN 		8
#define LCD_DB7_GPIO_CONFIG LCD_DB7_GPIO, LCD_DB7_PIN


#endif /* HD44780_HD44780_SETTINGS_H_ */
